---
title: "My English Activity Log : MEAL"
author:
  - name: "Lola Roseau" 
date: "`r Sys.Date()`"
categories:
  - "M.E.A.L."
output: distill::distill_article
---
21 September : Today, I had my first English lesson. I downloaded the BBC app, Quizlet and WordReference on my iPad.

27 September : I watched a new series called «To the lake». It is an epidemic story in Russia. We can’t watch it in French, it is only in English with French subtitles because the actors are Russian.

2 October : I talked with my Spanish friend on Instagram. I met her when I went to Los Angels in July 2019 to improve my English. We were on the same apartment so we became quickly friends. She didn’t went on the same school as me so we saw each other on our free time to do some expeditions. My best memory is when we went on the Griffith Observatory, the view was so amazing.

10 October : I read the BBC news every Saturday before my Monday English lesson. 

26 October : I really like to understand the lyrics of English songs. So yesterday I bought the new album of Ariana Grande (my favorite singer) and now I’m trying to translate the songs. Sometimes it’s a little bit too difficult so I search it on the internet. It's helpful to train my hearing skills. 

7 November : I watched some YouTube videos from one of my favorite American YouTuber, Bethany Mota. On her channel she talks about different subjects : decoration, diy, lifestyle...

20 November : «Emily in Paris» - I started to watch a new series about fashion and marketing. It’s the story of an American girl who comes in Paris to help an office with the marketing and the communication on the social networks. So obviously I had to watch it in English ! It is really more realistic because there are a lot of jokes on the fact that she doesn’t speak French.

December - January : It was the exams period so I didn’t have the time to do anything except studying. I made some synthesis for my English exams because finding the right tense was quite difficult for me. My exams were pretty good so I am happy ! 

20 February : I went to Natural Science Museum in Brussels, I tried to read the descriptions in English. I really enjoyed it, since my youngest age I go there very often. 

13 March : I started watching the series "Down to earth" on Netflix. This documentary series is about Zac Effron's journey through height incredible countries. In each country he talks about the nature and culture that enables us to live a sustainable and healthy life.

3 April : I went with my father at the battle of Waterloo museum. I decided to take the audio guide in English. It was really interesting, my father is really into History. 

2 May : Today, I did the last audits about my portfolio and my blog because I have to finish it for tomorrow.


